/* eslint-disable @typescript-eslint/no-unused-expressions */
/* eslint-disable @typescript-eslint/naming-convention */

import { describe, it, after } from 'mocha';
import { expect } from 'chai';
import nock from 'nock';
import {
  XandrClient,
  defaultApiUrl,
  getExpectedPlacement,
  getPlacementArchetype,
  validatePlacementArchetype,
  verifyPlacement
} from '../src/index';
import type { Placement, PlacementDimensions } from '../src/placement/types';

const endpoint = '/placement';

const displayDesktop: PlacementDimensions = {
  environments: ['web'], channels: ['display'], formats: ['banner'], ad_positions: ['top']
};

const instreamVideo: PlacementDimensions = {
  environments: ['web'], channels: ['video'], formats: ['video_instream'], ad_positions: ['midroll']
};

const outstreamVideo: PlacementDimensions = {
  environments: ['web'], channels: ['video'], formats: ['video_outstream'], ad_positions: ['incontent']
};

const nativeWeb: PlacementDimensions = {
  environments: ['web'], channels: ['native'], formats: ['native']
};

const interstitialApp: PlacementDimensions = {
  environments: ['app'], channels: ['display'], formats: ['interstitial'], ad_positions: ['fullscreen']
};

const interstitialWeb: PlacementDimensions = { ...interstitialApp, environments: ['web'] };

const skinWeb: PlacementDimensions = {
  environments: ['web'], channels: ['display'], formats: ['skin'], ad_positions: ['static']
};

const audioWeb: PlacementDimensions = {
  environments: ['web'], channels: ['audio'], formats: ['audio']
};

const bannerMediaType = { id: 1, name: 'Banner', is_private: false };
const interstitialMediaType = { id: 3, name: 'Interstitial', is_private: false };
const videoMediaType = { id: 4, name: 'Video', is_private: false };
const skinMediaType = { id: 8, name: 'Skin', is_private: false };
const nativeMediaType = { id: 12, name: 'Native', is_private: false };

const videoAdType = {
  id: 2, name: 'video', display_name: 'Video',
  renderer: { id: 2, display_name: 'Generated by CAPI', config: null }
};

const nativeAdType = {
  id: 3, name: 'native', display_name: 'Native',
  renderer: { id: 13859, display_name: 'Adaptive renderer', config: 'null' }
};

function xandrPlacement (fields: Record<string, unknown>): Placement {
  return {
    id: 1,
    name: 'spec',
    state: 'active',
    width: null,
    height: null,
    is_resizable: true,
    supported_media_types: [bannerMediaType],
    ad_types: null,
    video: null,
    ...fields
  } as unknown as Placement;
}

const bannerPlacement = xandrPlacement({});

const interstitialPlacement = xandrPlacement({ supported_media_types: [interstitialMediaType], width: 1, height: 1 });

const instreamPlacement = xandrPlacement({
  supported_media_types: [videoMediaType], width: 1, height: 1, ad_types: [],
  video: { context: 'mid-roll', start_delay_secs: 15, supports_skippable: true }
});

const outstreamPlacement = xandrPlacement({
  supported_media_types: [videoMediaType], width: 1, height: 1, ad_types: [videoAdType],
  video: { context: 'outstream', start_delay_secs: 0, supports_skippable: false }
});

const skinPlacement = xandrPlacement({ supported_media_types: [skinMediaType] });

const nativePlacement = xandrPlacement({ supported_media_types: [nativeMediaType], width: 1, height: 1, ad_types: [nativeAdType] });

describe('Placement validation: expected placement', () => {

  it('derives the archetype from the dimensions', () => {
    expect(getExpectedPlacement(displayDesktop)?.type).to.equal('banner');
    expect(getExpectedPlacement(instreamVideo)?.type).to.equal('video-instream');
    expect(getExpectedPlacement(outstreamVideo)?.type).to.equal('video-outstream');
    expect(getExpectedPlacement(nativeWeb)?.type).to.equal('native');
    expect(getExpectedPlacement(interstitialApp)?.type).to.equal('interstitial');
    expect(getExpectedPlacement(skinWeb)?.type).to.equal('skin');
  });

  it('builds the full expected placement', () => {
    expect(getExpectedPlacement(outstreamVideo)).to.deep.equal({
      type: 'video-outstream',
      width: 1,
      height: 1,
      is_resizable: true,
      supported_media_types: [videoMediaType],
      ad_types: [videoAdType],
      video: { context: 'outstream' }
    });
    expect(getExpectedPlacement(nativeWeb)).to.deep.equal({
      type: 'native',
      width: 1,
      height: 1,
      is_resizable: true,
      supported_media_types: [nativeMediaType],
      ad_types: [nativeAdType],
      video: null
    });
  });

  it('sizes the interstitial 1x1 on app and leaves it unsized on web', () => {
    expect(getExpectedPlacement(interstitialApp)).to.include({ type: 'interstitial', width: 1, height: 1, video: null, is_resizable: true });
    expect(getExpectedPlacement(interstitialWeb)).to.include({ type: 'interstitial', width: null, height: null });
  });

  it('gives the interstitial and skin formats precedence over the channel', () => {
    expect(getExpectedPlacement({ ...instreamVideo, formats: ['interstitial', 'video_instream'] })?.type).to.equal('interstitial');
    expect(getExpectedPlacement({ ...nativeWeb, formats: ['skin'] })?.type).to.equal('skin');
    expect(getExpectedPlacement({ ...skinWeb, formats: ['skin', 'interstitial'] })?.type).to.equal('interstitial');
    expect(getExpectedPlacement({ ...displayDesktop, channels: ['video', 'display'] })?.type).to.equal('banner');
  });

  it('maps the instream ad positions to the Xandr video context, preroll first', () => {
    expect(getExpectedPlacement(instreamVideo)?.video).to.deep.equal({ context: 'mid-roll' });
    expect(getExpectedPlacement({ ...instreamVideo, ad_positions: ['midroll', 'preroll'] })?.video).to.deep.equal({ context: 'pre-roll' });
    expect(getExpectedPlacement({ ...instreamVideo, ad_positions: ['postroll', 'midroll'] })?.video).to.deep.equal({ context: 'mid-roll' });
    expect(getExpectedPlacement({ ...instreamVideo, ad_positions: ['postroll'] })?.video).to.deep.equal({ context: 'post-roll' });
    expect(getExpectedPlacement({ ...instreamVideo, ad_positions: ['player'] })?.video).to.deep.equal({ context: 'pre-roll' });
    expect(getExpectedPlacement({ ...instreamVideo, ad_positions: null })?.video).to.deep.equal({ context: 'pre-roll' });
  });

  it('returns null for dimensions no archetype handles', () => {
    expect(getExpectedPlacement(audioWeb)).to.be.null;
    expect(getExpectedPlacement({ ...instreamVideo, formats: ['rewarded_video'] })).to.be.null;
    expect(getExpectedPlacement({})).to.be.null;
    expect(getExpectedPlacement({ channels: null, formats: null, ad_positions: null, environments: null })).to.be.null;
  });

  it('reads the ad positions of a wrapper row passed as is', () => {
    const row = { id: 'uuid', name: 'row', channels: ['video'], formats: ['video_instream'], ad_positions: ['midroll'], environments: ['web'] };
    expect(getExpectedPlacement(row)?.video).to.deep.equal({ context: 'mid-roll' });
  });

  it('returns a fresh object on every call', () => {
    const first = getExpectedPlacement(nativeWeb);
    if (first?.type !== 'native')
      throw new Error('expected a native placement');
    first.ad_types[0].renderer.display_name = 'mutated' as 'Adaptive renderer';
    expect(getExpectedPlacement(nativeWeb)).to.deep.include({ ad_types: [nativeAdType] });
  });
});

describe('Placement validation: Xandr archetype detection', () => {

  it('detects every archetype', () => {
    expect(getPlacementArchetype(bannerPlacement)).to.equal('banner');
    expect(getPlacementArchetype(interstitialPlacement)).to.equal('interstitial');
    expect(getPlacementArchetype(instreamPlacement)).to.equal('video-instream');
    expect(getPlacementArchetype(outstreamPlacement)).to.equal('video-outstream');
    expect(getPlacementArchetype(skinPlacement)).to.equal('skin');
    expect(getPlacementArchetype(nativePlacement)).to.equal('native');
  });

  it('prefers interstitial, then skin, then banner, then video, then native', () => {
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: [bannerMediaType, interstitialMediaType] }))).to.equal('interstitial');
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: [bannerMediaType, skinMediaType] }))).to.equal('skin');
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: [nativeMediaType, bannerMediaType] }))).to.equal('banner');
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: [nativeMediaType, videoMediaType], video: { context: 'pre-roll' } }))).to.equal('video-instream');
  });

  it('returns null for an unknown video context or media type', () => {
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: [videoMediaType], video: null }))).to.be.null;
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: [videoMediaType], video: { context: 'unknown' } }))).to.be.null;
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: [{ id: 11, name: 'High Impact' }] }))).to.be.null;
    expect(getPlacementArchetype(xandrPlacement({ supported_media_types: null }))).to.be.null;
  });
});

describe('Placement validation: archetype fields', () => {

  it('accepts the placements Xandr holds for every archetype', () => {
    expect(validatePlacementArchetype(bannerPlacement, 'banner')).to.deep.equal([]);
    expect(validatePlacementArchetype(xandrPlacement({ ad_types: [] }), 'banner')).to.deep.equal([]);
    expect(validatePlacementArchetype(interstitialPlacement, 'interstitial')).to.deep.equal([]);
    expect(validatePlacementArchetype(instreamPlacement, 'video-instream')).to.deep.equal([]);
    expect(validatePlacementArchetype(outstreamPlacement, 'video-outstream')).to.deep.equal([]);
    expect(validatePlacementArchetype(skinPlacement, 'skin')).to.deep.equal([]);
    expect(validatePlacementArchetype(nativePlacement, 'native')).to.deep.equal([]);
  });

  it('accepts a sized or unsized interstitial whatever the environment', () => {
    expect(validatePlacementArchetype(xandrPlacement({ supported_media_types: [interstitialMediaType] }), 'interstitial')).to.deep.equal([]);
  });

  it('accepts every instream roll context', () => {
    for (const context of ['pre-roll', 'mid-roll', 'post-roll'])
      expect(validatePlacementArchetype(xandrPlacement({ ...instreamPlacement, video: { context } }), 'video-instream')).to.deep.equal([]);
  });

  it('reports every diverging field with its path', () => {
    const issues = validatePlacementArchetype(xandrPlacement({
      width: 300,
      height: 250,
      is_resizable: false,
      supported_media_types: [{ ...bannerMediaType, is_private: true }],
      ad_types: [videoAdType],
      video: undefined
    }), 'banner');

    expect(issues.map(issue => issue.path)).to.deep.equal([
      'width',
      'height',
      'is_resizable',
      'supported_media_types.0.is_private',
      'ad_types',
      'video'
    ]);
    expect(issues[0]).to.deep.equal({ path: 'width', expected: 'null', received: 300, message: 'expected null, received 300' });
    expect(issues[5].message).to.equal('expected null, received undefined');
  });

  it('checks the nested video and ad type fields', () => {
    expect(validatePlacementArchetype(xandrPlacement({ ...instreamPlacement, video: { context: 'outstream' } }), 'video-instream'))
      .to.have.nested.property('[0].path', 'video.context');
    expect(validatePlacementArchetype(xandrPlacement({ ...outstreamPlacement, video: null }), 'video-outstream'))
      .to.deep.equal([{ path: 'video', expected: 'an object', received: null, message: 'expected an object, received null' }]);

    const nativeIssues = validatePlacementArchetype(xandrPlacement({
      ...nativePlacement,
      ad_types: [{ ...nativeAdType, renderer: { ...nativeAdType.renderer, config: null } }]
    }), 'native');
    expect(nativeIssues.map(issue => issue.path)).to.deep.equal(['ad_types.0.renderer.config']);
    expect(nativeIssues[0].message).to.equal('expected "null", received null');
  });

  it('accepts a media type without is_private', () => {
    expect(validatePlacementArchetype(xandrPlacement({ supported_media_types: [{ id: 1, name: 'Banner' }] }), 'banner')).to.deep.equal([]);
    expect(validatePlacementArchetype(xandrPlacement({ supported_media_types: [{ ...bannerMediaType, is_private: true }] }), 'banner'))
      .to.have.nested.property('[0].path', 'supported_media_types.0.is_private');
  });

  it('describes circular, bigint and non finite values without throwing', () => {
    const circular: Record<string, unknown> = {};
    circular.self = circular;
    const issues = validatePlacementArchetype(xandrPlacement({ video: circular, width: BigInt(1), height: NaN }), 'banner');
    expect(issues.map(issue => issue.message)).to.deep.equal([
      'expected null, received 1n',
      'expected null, received NaN',
      'expected null, received [object Object]'
    ]);
  });

  it('rejects a missing array', () => {
    expect(validatePlacementArchetype(xandrPlacement({ ...outstreamPlacement, ad_types: null }), 'video-outstream'))
      .to.deep.equal([{ path: 'ad_types', expected: 'an array', received: null, message: 'expected an array, received null' }]);
  });
});

describe('Placement validation: verification', () => {

  const placementId = 42;

  it('reports a conform placement', () => {
    const verification = verifyPlacement({ placementId, dimensions: instreamVideo }, instreamPlacement);

    expect(verification.status).to.equal('CONFORM');
    expect(verification.expectedType).to.equal('video-instream');
    expect(verification.actualType).to.equal('video-instream');
    expect(verification.issues).to.deep.equal([]);
    expect(verification.reason).to.be.null;
  });

  it('reports unhandled dimensions before checking the placement exists', () => {
    const verification = verifyPlacement({ placementId, dimensions: audioWeb }, null);

    expect(verification.status).to.equal('UNHANDLED_DIMS');
    expect(verification.expected).to.be.null;
    expect(verification.reason).to.contain('channels=[audio]');
  });

  it('reports an absent placement', () => {
    const verification = verifyPlacement({ placementId, dimensions: displayDesktop }, null);

    expect(verification.status).to.equal('ABSENT');
    expect(verification.expectedType).to.equal('banner');
    expect(verification.actualType).to.be.null;
    expect(verification.placement).to.be.null;
  });

  it('skips a multi media-type placement before comparing the types', () => {
    const verification = verifyPlacement(
      { placementId, dimensions: nativeWeb },
      xandrPlacement({ supported_media_types: [bannerMediaType, nativeMediaType] })
    );

    expect(verification.status).to.equal('MULTI_MEDIA_TYPE');
    expect(verification.actualType).to.equal('banner');
  });

  it('reports a type mismatch', () => {
    const verification = verifyPlacement({ placementId, dimensions: outstreamVideo }, instreamPlacement);

    expect(verification.status).to.equal('TYPE_MISMATCH');
    expect(verification.expectedType).to.equal('video-outstream');
    expect(verification.actualType).to.equal('video-instream');

    const unknownVerification = verifyPlacement({ placementId, dimensions: displayDesktop }, xandrPlacement({ supported_media_types: [] }));
    expect(unknownVerification.status).to.equal('TYPE_MISMATCH');
    expect(unknownVerification.actualType).to.be.null;
    expect(unknownVerification.reason).to.contain('holds a unknown one');
  });

  it('reports an instream context other than the ad positions call for', () => {
    const verification = verifyPlacement(
      { placementId, dimensions: instreamVideo },
      xandrPlacement({ ...instreamPlacement, video: { context: 'pre-roll' } })
    );

    expect(verification.status).to.equal('FIELD_MISMATCH');
    expect(verification.issues).to.deep.equal([
      { path: 'video.context', expected: '"mid-roll"', received: 'pre-roll', message: 'expected "mid-roll", received "pre-roll"' }
    ]);
  });

  it('reports a field mismatch with its issues', () => {
    const verification = verifyPlacement({ placementId, dimensions: displayDesktop }, xandrPlacement({ width: 300, height: 250 }));

    expect(verification.status).to.equal('FIELD_MISMATCH');
    expect(verification.issues.map(issue => issue.path)).to.deep.equal(['width', 'height']);
    expect(verification.reason).to.equal('fields diverge from the expected banner placement: width: expected null, received 300 | height: expected null, received 250');
  });
});

describe('Placement API verify (nock intercepted)', () => {

  const username = 'x';
  const password = 'x';

  function placementsResponse (placements: Placement[]): Record<string, unknown> {
    return { response: { status: 'OK', count: placements.length, start_element: 0, num_elements: 100, placements }};
  }

  after(() => {
    nock.cleanAll();
  });

  it('fetches the placements by batch and keeps the targets order', async () => {
    const client = new XandrClient({ username, password });
    nock(defaultApiUrl).post('/auth').reply(200, { response: { token: 'token' }});
    const firstBatch = nock(defaultApiUrl).get(endpoint).query({ start_element: '0', id: '1,2' })
      .reply(200, placementsResponse([xandrPlacement({ id: 1 }), xandrPlacement({ id: 2, width: 300 })]));
    const secondBatch = nock(defaultApiUrl).get(endpoint).query({ start_element: '0', id: '3' })
      .reply(200, placementsResponse([]));

    const verifications = await client.placement.verify([
      { placementId: 1, dimensions: displayDesktop },
      { placementId: 2, dimensions: displayDesktop },
      { placementId: 1, dimensions: nativeWeb },
      { placementId: 3, dimensions: displayDesktop }
    ], { batchSize: 2 });

    expect(firstBatch.isDone()).to.be.true;
    expect(secondBatch.isDone()).to.be.true;
    expect(verifications.map(verification => [verification.placementId, verification.status])).to.deep.equal([
      [1, 'CONFORM'],
      [2, 'FIELD_MISMATCH'],
      [1, 'TYPE_MISMATCH'],
      [3, 'ABSENT']
    ]);
  });

  it('flags the placements of a failed batch without stopping the others', async () => {
    const client = new XandrClient({ username, password });
    nock(defaultApiUrl).post('/auth').reply(200, { response: { token: 'token' }});
    nock(defaultApiUrl).get(endpoint).query({ start_element: '0', id: '1' })
      .reply(500, { response: { error: 'boom', error_id: 'SYSTEM' }});
    nock(defaultApiUrl).get(endpoint).query({ start_element: '0', id: '2' })
      .reply(200, placementsResponse([xandrPlacement({ id: 2 })]));

    const verifications = await client.placement.verify([
      { placementId: 1, dimensions: displayDesktop },
      { placementId: 2, dimensions: displayDesktop }
    ], { batchSize: 1 });

    expect(verifications[0].status).to.equal('GET_FAILED');
    expect(verifications[0].expectedType).to.equal('banner');
    expect(verifications[0].actualType).to.be.null;
    expect(String(verifications[0].error)).to.contain('boom');
    expect(verifications[1].status).to.equal('CONFORM');
  });

  it('flags the placements of a batch that times out', async () => {
    const client = new XandrClient({ username, password });
    nock(defaultApiUrl).post('/auth').reply(200, { response: { token: 'token' }});
    nock(defaultApiUrl).get(endpoint).query(true).delay(300)
      .reply(200, placementsResponse([xandrPlacement({ id: 1 })]));

    const verifications = await client.placement.verify([{ placementId: 1, dimensions: displayDesktop }], { timeoutMs: 50 });

    expect(verifications[0].status).to.equal('GET_FAILED');
    expect(String(verifications[0].error)).to.contain('did not settle within 50ms');
  });

  it('stops paging when the response carries no count or an empty page', async () => {
    const client = new XandrClient({ username, password });
    nock(defaultApiUrl).post('/auth').reply(200, { response: { token: 'token' }});
    nock(defaultApiUrl).get(endpoint).query(true).reply(200, { response: { status: 'OK', placements: [xandrPlacement({ id: 1 })] }});
    nock(defaultApiUrl).get(endpoint).query(true).reply(200, { response: { status: 'OK', count: 5, placements: [xandrPlacement({ id: 2 })] }});
    const lastPage = nock(defaultApiUrl).get(endpoint).query({ start_element: '1', id: '2' }).reply(200, { response: { status: 'OK', count: 5, placements: [] }});

    expect((await client.placement.get({ placementIds: [1] })).length).to.equal(1);
    expect((await client.placement.get({ placementIds: [2] })).length).to.equal(1);
    expect(lastPage.isDone()).to.be.true;
  });

  it('rejects invalid options', async () => {
    const client = new XandrClient({ username, password });

    for (const options of [{ batchSize: 0 }, { batchSize: 1.5 }, { timeoutMs: 0 }, { timeoutMs: Infinity }]) {
      let error: unknown = null;
      try {
        await client.placement.verify([{ placementId: 1, dimensions: displayDesktop }], options);
      } catch (caught: unknown) {
        error = caught;
      }
      expect(error).to.be.instanceOf(Error);
    }
  });
});
