/* eslint-disable @typescript-eslint/naming-convention */

import type {
  Advertiser
} from '../advertiser/types';

import type {
  InventoryAttribute
} from '../inventory-attribute/types';

import type {
  LineItem
} from '../line-item/types';

import type {
  Segment
} from '../segment/types';

import type {
  CommonResponse,
  State,
  PlacementPosition,
  IdName
} from '../xandr-types';



interface DefaultCreative {
  id: number;
  width: number;
  height: number;
  price: number;
  name: string;
}

interface ContentCategory {
  code: string;
  description: string;
  id: number;
  is_system: boolean;
  last_modified: string;
  member_id: number;
  name: string;
  parent_category: {
    id: number;
    name: string;
  };
  type:  'deal_priority' | 'deal' | 'standard';
}

interface PlacementAdType {
  id: number;
  renderer_id: number;
  name: string;
  display_name: string;
  renderer: {
    id: string;
    display_name: string;
  };
}

interface VideoSettings {
  id: number;
  width: number;
  max_duration_secs: number;
  maximum_ad_duration_secs: number;
  maximum_number_ads: number;
  start_delay_secs: number;
  skipoffset_seconds: number;
  supports_skippable: boolean;
  context: string;
  playback_method: 'auto_play_sound_off' | 'auto_play_sound_off' | 'auto_play_sound_on' | 'auto_play_sound_unknown' | 'mouse_over' | null;
  frameworks: ('mraid_1' | 'mraid_2' | 'ormma' | 'vpaid_1_0' | 'vpaid_2_0')[];
  video_bumpers: {
    video_bumper_type: 'intro' | 'outro';
    max_duration_secs: number | null;
  };
  player_vast_version: string;
  vmin_ad_duration: number;
  minbitrate: number;
  mf_min_width: number;
  mf_min_height: number;
}

export interface PlacementInput {
  name: string;
  code?: string | null;
  code2?: string | null;
  code3?: string | null;
  state?: State;
  width?: number | null;
  height?: number | null;
  is_resizable?: boolean;
  default_position?: PlacementPosition;
  publisher_id: number;
  site_id?: number;
  ad_profile_id?: number | null;
  supported_media_types?: IdName[] | null;
  supported_media_subtypes?: IdName[] | null;
  default_creatives?: DefaultCreative[];
  reserve_price?: number;
  hide_referer?: boolean;
  default_referrer_url?: string | null;
  visibility_profile_id?: number;
  pixel_url?: string | null;
  pixel_type?: 'image' | 'javascript';
  content_categories?: ContentCategory[];
  filtered_advertisers?: Advertiser[] | null;
  filtered_line_items?: LineItem[] | null;
  filtered_campaigns?: null;
  segments?: Segment[] | null;
  intended_audience?: 'children' | 'general' | 'mature' | 'young_adult';
  inventory_attributes?: InventoryAttribute[] | null;
  audited?: boolean;
  audit_level?: 'placement' | 'site';
  default_calculcation_type?: 'gross' | 'net';
  demand_filter_action?: string;
  floor_application_target?: 'all' | 'external_non_preferred' | 'external_only';
  pixel_url_secure?: string;
  site_audit_status?: 'self' | 'unaudited';
  is_prohibited?: boolean;
  cost_cpm?: number;
  content_retrieval_timeout_ms?: number;
  enable_for_mediation?: boolean;
  private_sizes?: {
    width: number;
    height: number;
  }[];
  sizes?: {
    width: number;
    height: number;
  }[];
  video?: Partial<VideoSettings> | null;
  ad_types?: PlacementAdType[];
  use_detected_domain?: boolean;
  mime_types?: string[];
  supported_mime_types_action_include?: boolean;
  handles_mixed_media?: boolean;
  tinytag_renderer_asset_floor_prices?: {
    renderer_id: number;
    ad_type_id: number;
    asset_type: number;
    floor_price: number;
  }[];
}

export type Placement = Required<PlacementInput> & {
  id: number;
  site_name: string;
  exclusive: boolean;
};

export type GetPlacementParams = {
  placementIds: number[];
} | {
  publisherId: number;
};

export type CreatePlacementParams = {
  publisherId: number;
} | {
  siteId: number;
};

export type ModifyPlacementParams = {
  placementId: number;
} & ({
  publisherId: number;
} | {
  siteId: number;
});

export type PlacementResponse = CommonResponse & {
  placement?: Placement;
  placements?: Placement[];
};

export type InstreamVideoContext = 'mid-roll' | 'post-roll' | 'pre-roll';

export interface PlacementDimensions {
  channels?: readonly string[] | null;
  formats?: readonly string[] | null;
  adPositions?: readonly string[] | null;
  environments?: readonly string[] | null;
  ad_positions?: never;
}

export interface ExpectedMediaType<TId extends number, TName extends string> {
  id: TId;
  name: TName;
  is_private: false;
}

export interface ExpectedVideoAdType {
  id: 2;
  name: 'video';
  display_name: 'Video';
  renderer: {
    id: 2;
    display_name: 'Generated by CAPI';
    config: null;
  };
}

export interface ExpectedNativeAdType {
  id: 3;
  name: 'native';
  display_name: 'Native';
  renderer: {
    id: 13859;
    display_name: 'Adaptive renderer';
    config: 'null';
  };
}

export interface ExpectedBannerPlacement {
  type: 'banner';
  width: null;
  height: null;
  is_resizable: true;
  supported_media_types: ExpectedMediaType<1, 'Banner'>[];
  ad_types: never[];
  video: null;
}

export interface ExpectedInterstitialPlacement {
  type: 'interstitial';
  width: 1 | null;
  height: 1 | null;
  is_resizable: true;
  supported_media_types: ExpectedMediaType<3, 'Interstitial'>[];
  ad_types: never[];
  video: null;
}

export interface ExpectedInstreamVideoPlacement {
  type: 'video-instream';
  width: 1;
  height: 1;
  is_resizable: true;
  supported_media_types: ExpectedMediaType<4, 'Video'>[];
  ad_types: never[];
  video: {
    context: InstreamVideoContext;
  };
}

export interface ExpectedOutstreamVideoPlacement {
  type: 'video-outstream';
  width: 1;
  height: 1;
  is_resizable: true;
  supported_media_types: ExpectedMediaType<4, 'Video'>[];
  ad_types: ExpectedVideoAdType[];
  video: {
    context: 'outstream';
  };
}

export interface ExpectedSkinPlacement {
  type: 'skin';
  width: null;
  height: null;
  is_resizable: true;
  supported_media_types: ExpectedMediaType<8, 'Skin'>[];
  ad_types: never[];
  video: null;
}

export interface ExpectedNativePlacement {
  type: 'native';
  width: 1;
  height: 1;
  is_resizable: true;
  supported_media_types: ExpectedMediaType<12, 'Native'>[];
  ad_types: ExpectedNativeAdType[];
  video: null;
}

export type ExpectedPlacement = (
  ExpectedBannerPlacement |
  ExpectedInstreamVideoPlacement |
  ExpectedInterstitialPlacement |
  ExpectedNativePlacement |
  ExpectedOutstreamVideoPlacement |
  ExpectedSkinPlacement
);

export type PlacementArchetype = ExpectedPlacement['type'];

export interface PlacementFieldIssue {
  path: string;
  expected: string;
  received: unknown;
  message: string;
}

export type PlacementVerificationStatus = (
  'ABSENT' |
  'CONFORM' |
  'FIELD_MISMATCH' |
  'GET_FAILED' |
  'MULTI_MEDIA_TYPE' |
  'TYPE_MISMATCH' |
  'UNHANDLED_DIMS'
);

export interface PlacementVerificationTarget {
  placementId: number;
  dimensions: PlacementDimensions;
}

export interface PlacementVerification {
  placementId: number;
  status: PlacementVerificationStatus;
  expected: ExpectedPlacement | null;
  expectedType: PlacementArchetype | null;
  actualType: PlacementArchetype | null;
  placement: Placement | null;
  issues: PlacementFieldIssue[];
  reason: string | null;
  error?: unknown;
}

export interface VerifyPlacementOptions {
  batchSize?: number;
  timeoutMs?: number;
}