/* eslint-disable @typescript-eslint/naming-convention */
import type {
  ExpectedMediaType,
  ExpectedNativeAdType,
  ExpectedPlacement,
  ExpectedVideoAdType,
  InstreamVideoContext,
  Placement,
  PlacementArchetype,
  PlacementDimensions,
  PlacementFieldIssue,
  PlacementVerification,
  PlacementVerificationTarget
} from './types';

type FieldRule = (value: unknown, path: string, issues: PlacementFieldIssue[]) => void;

const INSTREAM_VIDEO_CONTEXTS: InstreamVideoContext[] = [ 'pre-roll', 'mid-roll', 'post-roll' ];

function mediaType<TId extends number, TName extends string> (id: TId, name: TName): ExpectedMediaType<TId, TName> {
  return { id, name, is_private: false };
}

function videoAdType (): ExpectedVideoAdType {
  return {
    id: 2,
    name: 'video',
    display_name: 'Video',
    renderer: { id: 2, display_name: 'Generated by CAPI', config: null }
  };
}

function nativeAdType (): ExpectedNativeAdType {
  return {
    id: 3,
    name: 'native',
    display_name: 'Native',
    renderer: { id: 13859, display_name: 'Adaptive renderer', config: 'null' }
  };
}

function childPath (path: string, key: number | string): string {
  return path === '' ? String(key) : `${path}.${key}`;
}

function describeValue (value: unknown): string {
  if (value === undefined)
    return 'undefined';
  if (typeof value === 'bigint')
    return `${value}n`;
  if (typeof value === 'number' && !Number.isFinite(value))
    return String(value);
  try {
    return JSON.stringify(value);
  } catch {
    return Object.prototype.toString.call(value);
  }
}

function addIssue (issues: PlacementFieldIssue[], path: string, expected: string, received: unknown): void {
  issues.push({ path, expected, received, message: `expected ${expected}, received ${describeValue(received)}` });
}

function isRecord (value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function oneOf (...allowed: unknown[]): FieldRule {
  const expected = allowed.map(describeValue).join(' | ');
  return (value, path, issues): void => {
    if (!allowed.includes(value))
      addIssue(issues, path, expected, value);
  };
}

function shape (rules: Record<string, FieldRule>): FieldRule {
  return (value, path, issues): void => {
    if (!isRecord(value)) {
      addIssue(issues, path, 'an object', value);
      return;
    }
    for (const [key, rule] of Object.entries(rules))
      rule(value[key], childPath(path, key), issues);
  };
}

function arrayOf (rule: FieldRule): FieldRule {
  return (value, path, issues): void => {
    if (!Array.isArray(value)) {
      addIssue(issues, path, 'an array', value);
      return;
    }
    value.forEach((item: unknown, index): void => {
      rule(item, childPath(path, index), issues);
    });
  };
}

function exactly (expected: unknown): FieldRule {
  if (!isRecord(expected))
    return oneOf(expected);
  return shape(Object.fromEntries(
    Object.entries(expected).map(([key, value]): [string, FieldRule] => [key, exactly(value)])
  ));
}

function mediaTypeRule (id: number, name: string): FieldRule {
  return shape({ id: oneOf(id), name: oneOf(name), is_private: oneOf(false, undefined) });
}

function emptyArrayOrNull (value: unknown, path: string, issues: PlacementFieldIssue[]): void {
  if (value !== null && !(Array.isArray(value) && value.length === 0))
    addIssue(issues, path, 'an empty array or null', value);
}

const ARCHETYPE_RULES: Record<PlacementArchetype, Record<string, FieldRule>> = {
  'banner': {
    width: oneOf(null),
    height: oneOf(null),
    is_resizable: oneOf(true),
    supported_media_types: arrayOf(mediaTypeRule(1, 'Banner')),
    ad_types: emptyArrayOrNull,
    video: oneOf(null)
  },
  'interstitial': {
    width: oneOf(1, null),
    height: oneOf(1, null),
    is_resizable: oneOf(true),
    supported_media_types: arrayOf(mediaTypeRule(3, 'Interstitial')),
    ad_types: emptyArrayOrNull,
    video: oneOf(null)
  },
  'video-instream': {
    width: oneOf(1),
    height: oneOf(1),
    is_resizable: oneOf(true),
    supported_media_types: arrayOf(mediaTypeRule(4, 'Video')),
    ad_types: emptyArrayOrNull,
    video: shape({ context: oneOf(...INSTREAM_VIDEO_CONTEXTS) })
  },
  'video-outstream': {
    width: oneOf(1),
    height: oneOf(1),
    is_resizable: oneOf(true),
    supported_media_types: arrayOf(mediaTypeRule(4, 'Video')),
    ad_types: arrayOf(exactly(videoAdType())),
    video: shape({ context: oneOf('outstream') })
  },
  'skin': {
    width: oneOf(null),
    height: oneOf(null),
    is_resizable: oneOf(true),
    supported_media_types: arrayOf(mediaTypeRule(8, 'Skin')),
    ad_types: emptyArrayOrNull,
    video: oneOf(null)
  },
  'native': {
    width: oneOf(1),
    height: oneOf(1),
    is_resizable: oneOf(true),
    supported_media_types: arrayOf(mediaTypeRule(12, 'Native')),
    ad_types: arrayOf(exactly(nativeAdType())),
    video: oneOf(null)
  }
};

function getInstreamVideoContext (adPositions: readonly string[]): InstreamVideoContext {
  if (adPositions.includes('preroll'))
    return 'pre-roll';
  if (adPositions.includes('midroll'))
    return 'mid-roll';
  if (adPositions.includes('postroll'))
    return 'post-roll';
  return 'pre-roll';
}

function describeDimensions (dimensions: PlacementDimensions): string {
  return [
    `channels=[${(dimensions.channels ?? []).join(', ')}]`,
    `formats=[${(dimensions.formats ?? []).join(', ')}]`,
    `ad_positions=[${(dimensions.ad_positions ?? []).join(', ')}]`,
    `environments=[${(dimensions.environments ?? []).join(', ')}]`
  ].join(' ');
}

function describeIssues (issues: PlacementFieldIssue[]): string {
  return issues.map((issue): string => `${issue.path}: ${issue.message}`).join(' | ');
}

export function getExpectedPlacement (dimensions: PlacementDimensions): ExpectedPlacement | null {
  const channels = dimensions.channels ?? [];
  const formats = dimensions.formats ?? [];
  const environments = dimensions.environments ?? [];

  if (formats.includes('interstitial')) {
    const isApp = environments.includes('app');
    return {
      type: 'interstitial',
      width: isApp ? 1 : null,
      height: isApp ? 1 : null,
      is_resizable: true,
      supported_media_types: [ mediaType(3, 'Interstitial') ],
      ad_types: [],
      video: null
    };
  }

  if (formats.includes('skin')) {
    return {
      type: 'skin',
      width: null,
      height: null,
      is_resizable: true,
      supported_media_types: [ mediaType(8, 'Skin') ],
      ad_types: [],
      video: null
    };
  }

  if (channels.includes('display')) {
    return {
      type: 'banner',
      width: null,
      height: null,
      is_resizable: true,
      supported_media_types: [ mediaType(1, 'Banner') ],
      ad_types: [],
      video: null
    };
  }

  if (channels.includes('video')) {
    if (formats.includes('video_instream')) {
      return {
        type: 'video-instream',
        width: 1,
        height: 1,
        is_resizable: true,
        supported_media_types: [ mediaType(4, 'Video') ],
        ad_types: [],
        video: { context: getInstreamVideoContext(dimensions.ad_positions ?? []) }
      };
    }
    if (formats.includes('video_outstream')) {
      return {
        type: 'video-outstream',
        width: 1,
        height: 1,
        is_resizable: true,
        supported_media_types: [ mediaType(4, 'Video') ],
        ad_types: [ videoAdType() ],
        video: { context: 'outstream' }
      };
    }
    return null;
  }

  if (channels.includes('native')) {
    return {
      type: 'native',
      width: 1,
      height: 1,
      is_resizable: true,
      supported_media_types: [ mediaType(12, 'Native') ],
      ad_types: [ nativeAdType() ],
      video: null
    };
  }

  return null;
}

export function getPlacementArchetype (placement: Placement): PlacementArchetype | null {
  const supportedMediaTypes = placement.supported_media_types ?? [];
  const hasMediaType = (name: string): boolean => supportedMediaTypes.some((supportedMediaType): boolean => supportedMediaType.name === name);

  if (hasMediaType('Interstitial'))
    return 'interstitial';
  if (hasMediaType('Skin'))
    return 'skin';
  if (hasMediaType('Banner'))
    return 'banner';
  if (hasMediaType('Video')) {
    const context = placement.video?.context;
    if (INSTREAM_VIDEO_CONTEXTS.some((instreamContext): boolean => instreamContext === context))
      return 'video-instream';
    if (context === 'outstream')
      return 'video-outstream';
    return null;
  }
  if (hasMediaType('Native'))
    return 'native';
  return null;
}

export function validatePlacementArchetype (placement: Placement, archetype: PlacementArchetype): PlacementFieldIssue[] {
  const issues: PlacementFieldIssue[] = [];
  shape(ARCHETYPE_RULES[archetype])(placement, '', issues);
  return issues;
}

export function verifyPlacement (target: PlacementVerificationTarget, placement: Placement | null): PlacementVerification {
  const { placementId, dimensions } = target;
  const expected = getExpectedPlacement(dimensions);
  const actualType = placement === null ? null : getPlacementArchetype(placement);
  const verification: Omit<PlacementVerification, 'reason' | 'status'> = {
    placementId,
    expected,
    expectedType: expected?.type ?? null,
    actualType,
    placement,
    issues: []
  };

  if (expected === null) {
    return {
      ...verification,
      status: 'UNHANDLED_DIMS',
      reason: `the dimensions map to no known Xandr placement type: ${describeDimensions(dimensions)}`
    };
  }

  if (placement === null) {
    return {
      ...verification,
      status: 'ABSENT',
      reason: `placement ${placementId} does not exist in Xandr`
    };
  }

  const mediaTypeCount = (placement.supported_media_types ?? []).length;
  if (mediaTypeCount > 1) {
    return {
      ...verification,
      status: 'MULTI_MEDIA_TYPE',
      reason: `placement ${placementId} supports ${mediaTypeCount} media types, multi media-type placements are not verified`
    };
  }

  if (actualType !== expected.type) {
    return {
      ...verification,
      status: 'TYPE_MISMATCH',
      reason: `the dimensions expect a ${expected.type} placement, Xandr holds a ${actualType ?? 'unknown'} one (${describeDimensions(dimensions)})`
    };
  }

  const issues = validatePlacementArchetype(placement, expected.type);
  if (expected.type === 'video-instream' && !issues.some(issue => issue.path.startsWith('video')))
    oneOf(expected.video.context)(placement.video?.context, 'video.context', issues);
  if (issues.length > 0) {
    return {
      ...verification,
      status: 'FIELD_MISMATCH',
      issues,
      reason: `fields diverge from the expected ${expected.type} placement: ${describeIssues(issues)}`
    };
  }

  return {
    ...verification,
    status: 'CONFORM',
    reason: null
  };
}

export function getFailedVerification (target: PlacementVerificationTarget, error: unknown): PlacementVerification {
  const expected = getExpectedPlacement(target.dimensions);
  return {
    placementId: target.placementId,
    status: 'GET_FAILED',
    expected,
    expectedType: expected?.type ?? null,
    actualType: null,
    placement: null,
    issues: [],
    reason: `the Xandr GET call for placement ${target.placementId} failed, its conformity is unknown`,
    error
  };
}
